'use strict';

module.exports = {
    SET_API                             : 'SET_API',
    SET_TOKEN                           : 'SET_TOKEN',
    OAUTH_SET_CLIENT_OPTIONS            : 'OAUTH_SET_CLIENT_OPTIONS',
    REQUEST                             : 'REQUEST',
    REQUEST_SUCCESS                     : 'REQUEST_SUCCESS',
    REQUEST_FAILURE                     : 'REQUEST_FAILURE',
    REQUEST_ADD_TO_EXCLUDED_FIELDS      : 'REQUEST_ADD_TO_EXCLUDED_FIELDS',
    REQUEST_REMOVE_FROM_EXCLUDED_FIELDS : 'REQUEST_REMOVE_FROM_EXCLUDED_FIELDS',
    SET_REQUEST_VALUES                  : 'SET_REQUEST_VALUES',
    SET_NULL_VALUE                      : 'SET_NULL_VALUE',
    UNSET_NULL_VALUE                    : 'UNSET_NULL_VALUE',
    REQUEST_STRIPE_TOKEN                : 'REQUEST_STRIPE_TOKEN',
    REQUEST_STRIPE_TOKEN_SUCCESS        : 'REQUEST_STRIPE_TOKEN_SUCCESS',
    REQUEST_STRIPE_TOKEN_FAILURE        : 'REQUEST_STRIPE_TOKEN_FAILURE'
};
