'use strict';

module.exports = {
    OAUTH2_REQUEST         : 'OAUTH2_REQUEST',
    OAUTH2_REQUEST_SUCCESS : 'OAUTH2_REQUEST_SUCCESS',
    OAUTH2_REQUEST_FAILURE : 'OAUTH2_REQUEST_FAILURE',
    OAUTH2_SET_OPTIONS     : 'OAUTH2_SET_OPTIONS',
    OAUTH2_SET_TOKEN       : 'OAUTH2_SET_TOKEN',
};
